### PR TITLE
Add basic DDP

### PR DESCRIPTION
**Pull request by geekgonecrazy**
### Current State
- Establishes a connection using a component called `<rocketchat-connection>`
- Loads 100 Messages from the single room history
### Needs Improvement
- I'm browserify + babel to create a ddp.js shim using cli instead of as part of a build process.  `browserify app/scripts/ddp.js -o app/scripts/iddp.js  -t [ babelify --presets [ es2015 ] ]`
- Very reliant on gulp.  Need to reduce.
- Had to move away from `<iron-list>` because of the issue listed above.  We need something like this for performance. It recycles DOM elements instead of creating new ones. (https://github.com/Polymer/polymer/issues/3319 might be related)
- Need to get room message subscription working.
- Needs to get rooms from subscription instead of having to specify them.
### Example of component

Currently the component takes room.  Like mentioned in the needed improvements it should get this from the server or at least take an array

```
<rocketchat-connection url="wss://demo.rocket.chat" username="email@rocket.chat" password="superpassword" room="GENERAL" messages="{{messages}}"></rocketchat-connection>
```

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@dandv thoughts on this?  Any tips or ideas on structuring this?

**Comment by Sing-Li** [comment]
Refactored code into stand-alone, re-usable,  web components

**Comment by Sing-Li** [comment]
Add an iot canvas component for all the upcoming Maker Faires around the world early summer.

A special component for the Rocket.Chat on Raspberry Pi (RockOnPi) community.

Displays a PNG and allow "touch zones" to trigger SLASH CMDS sent to bots on a phone.

**Comment by geekgonecrazy** [comment]
No longer really relevant :)

**Pull request closed without merging**
