### PR TITLE
Improve UI Design

### PR DESCRIPTION
**Pull request by abdatta**
@karlprieb  Please review the changes made. Thank you. :)

### CODE REVIEW

**Comment by ajayns** [comment]
Can you please give screenshots of changes made? @abdatta

**Comment by abdatta** [comment]
image
image
In the second page, I've only solved that multiple scrollbars appearing at the side.

**Comment by ajayns** [comment]
@abdatta Great! That looks perfect, @InsaneNaman @karlprieb do check this PR out

**Comment by abdatta** [comment]
Thanks @ajayns ! I'm looking forward to do more contributions once @karlprieb checks this out.

**Comment by InsaneNaman** [comment]
Hey @abdatta thanks for the PR. It looks amazing. @karlprieb  Sir, can check the current status and merge it. 

@abdatta I would suggest to keep an eye on the lighthouse score as well side by side. :smile:

**Comment by karlprieb** [comment]
Hey @abdatta @InsaneNaman  I'll fix some conflicts on #32 and after that I'll merge this PR :)

**Comment by karlprieb** [comment]
@abdatta can you fix these conflicts?

**Comment by abdatta** [comment]
I've fixed the conflicts @karlprieb

**Review by karlprieb — APPROVED** [review]

**Pull request merged**
